"""add phone number

Revision ID: 879ba18fd913
Revises: 2a8c9595a220
Create Date: 2021-11-28 22:54:39.922466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879ba18fd913'
down_revision = '2a8c9595a220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('post-')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # op.create_table('post-',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='post_pkey')
    # )
    # ### end Alembic commands ###
